"""add pinterest csv export fields

Revision ID: 12e6cca5837c
Revises: a71e4445e5a7
Create Date: 2026-09-29 18:58:41.010350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e6cca5837c'
down_revision: Union[str, Sequence[str], None] = 'a71e4445e5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jerseys', sa.Column('pinterestExportedAt', sa.DateTime(), nullable=True))
    op.add_column('pinterest_integration', sa.Column('export_board_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinterest_integration', 'export_board_name')
    op.drop_column('jerseys', 'pinterestExportedAt')
    # ### end Alembic commands ###
