"""replace_download_url_with_r2_file_key

Revision ID: 2df651eb88c4
Revises: c2a2f1d892ca
Create Date: 2026-07-03 10:52:51.880843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2df651eb88c4'
down_revision: Union[str, Sequence[str], None] = 'c2a2f1d892ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.alter_column('cart_items', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('cart_items', 'cartId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('cart_items_cartId_jerseyId_key'), table_name='cart_items')
    op.create_unique_constraint('cart_items_cart_id_jersey_id_key', 'cart_items', ['cartId', 'jerseyId'])
    op.drop_constraint(op.f('cart_items_jerseyId_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_cartId_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cartId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'jerseys', ['jerseyId'], ['id'])
    op.alter_column('carts', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('carts', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('carts_userId_key'), table_name='carts')
    op.create_unique_constraint(None, 'carts', ['userId'])
    op.drop_constraint(op.f('carts_userId_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('categories', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('categories', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('jerseys', sa.Column('r2FileKey', sa.String(), nullable=True))
    op.alter_column('jerseys', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jerseys', 'player',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jerseys', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jerseys', 'badge',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jerseys', 'badgeColor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jerseys', 'categoryId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('jerseys_categoryId_fkey'), 'jerseys', type_='foreignkey')
    op.create_foreign_key(None, 'jerseys', 'categories', ['categoryId'], ['id'])
    op.drop_column('jerseys', 'downloadUrl')
    op.alter_column('order_items', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('order_items', 'orderId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('order_items_orderId_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_jerseyId_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'jerseys', ['jerseyId'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['orderId'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('downloadCount', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('orders', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('orders', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', name='OrderStatus'),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='orderstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'PENDING\'::"OrderStatus"'))
    op.drop_constraint(op.f('orders_userId_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['userId'], ['id'])
    op.alter_column('payments', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payments', 'orderId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='PaymentStatus'),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'PENDING\'::"PaymentStatus"'))
    op.alter_column('payments', 'transactionId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('payments_orderId_key'), table_name='payments')
    op.create_unique_constraint(None, 'payments', ['orderId'])
    op.drop_constraint(op.f('payments_orderId_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['orderId'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'companyName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='Role'),
               type_=sa.Enum('USER', 'ADMIN', name='role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'USER\'::"Role"'))
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('users_email_key'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('users_email_key'), 'users', ['email'], unique=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='role', native_enum=False),
               type_=postgresql.ENUM('USER', 'ADMIN', name='Role'),
               existing_nullable=False,
               existing_server_default=sa.text('\'USER\'::"Role"'))
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'companyName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_orderId_fkey'), 'payments', 'orders', ['orderId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index(op.f('payments_orderId_key'), 'payments', ['orderId'], unique=True)
    op.alter_column('payments', 'transactionId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='PaymentStatus'),
               existing_nullable=False,
               existing_server_default=sa.text('\'PENDING\'::"PaymentStatus"'))
    op.alter_column('payments', 'method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payments', 'orderId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_userId_fkey'), 'orders', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='orderstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', name='OrderStatus'),
               existing_nullable=False,
               existing_server_default=sa.text('\'PENDING\'::"OrderStatus"'))
    op.alter_column('orders', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('orders', 'downloadCount')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_jerseyId_fkey'), 'order_items', 'jerseys', ['jerseyId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('order_items_orderId_fkey'), 'order_items', 'orders', ['orderId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('order_items', 'orderId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('jerseys', sa.Column('downloadUrl', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jerseys', type_='foreignkey')
    op.create_foreign_key(op.f('jerseys_categoryId_fkey'), 'jerseys', 'categories', ['categoryId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('jerseys', 'categoryId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jerseys', 'badgeColor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jerseys', 'badge',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jerseys', 'image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jerseys', 'player',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jerseys', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('jerseys', 'r2FileKey')
    op.alter_column('categories', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_userId_fkey'), 'carts', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'carts', type_='unique')
    op.create_index(op.f('carts_userId_key'), 'carts', ['userId'], unique=True)
    op.alter_column('carts', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('carts', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_cartId_fkey'), 'cart_items', 'carts', ['cartId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('cart_items_jerseyId_fkey'), 'cart_items', 'jerseys', ['jerseyId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('cart_items_cart_id_jersey_id_key', 'cart_items', type_='unique')
    op.create_index(op.f('cart_items_cartId_jerseyId_key'), 'cart_items', ['cartId', 'jerseyId'], unique=True)
    op.alter_column('cart_items', 'cartId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cart_items', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    # ### end Alembic commands ###
