"""remove_categories

Revision ID: 333a688df245
Revises: ef74a5839223
Create Date: 2026-07-08 17:58:17.180352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333a688df245'
down_revision: Union[str, Sequence[str], None] = 'ef74a5839223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jerseys_categoryId_fkey'), 'jerseys', type_='foreignkey')
    op.drop_index(op.f('ix_jerseys_categoryId'), table_name='jerseys')
    op.drop_column('jerseys', 'categoryId')
    op.drop_table('categories')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'USER\'::"Role"'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='role', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text('\'USER\'::"Role"'))
    op.add_column('jerseys', sa.Column('categoryId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('jerseys_categoryId_fkey'), 'jerseys', 'categories', ['categoryId'], ['id'])
    op.create_index(op.f('ix_jerseys_categoryId'), 'jerseys', ['categoryId'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    # ### end Alembic commands ###
