"""remove dormant pinterest oauth columns

Revision ID: 6860eaf57cb4
Revises: 12e6cca5837c
Create Date: 2026-09-30 15:08:13.552953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6860eaf57cb4'
down_revision: Union[str, Sequence[str], None] = '12e6cca5837c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinterest_integration', 'access_token_expires_at')
    op.drop_column('pinterest_integration', 'access_token')
    op.drop_column('pinterest_integration', 'refresh_token')
    op.drop_column('pinterest_integration', 'board_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinterest_integration', sa.Column('board_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pinterest_integration', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pinterest_integration', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pinterest_integration', sa.Column('access_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
