"""drop_cart_tables_and_add_indexes

Revision ID: ef74a5839223
Revises: 2df651eb88c4
Create Date: 2026-07-04 11:34:07.208719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef74a5839223'
down_revision: Union[str, Sequence[str], None] = '2df651eb88c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.drop_table('carts')
    op.create_index(op.f('ix_jerseys_categoryId'), 'jerseys', ['categoryId'], unique=False)
    op.create_index(op.f('ix_orders_createdAt'), 'orders', ['createdAt'], unique=False)
    op.create_index(op.f('ix_orders_razorpayOrderId'), 'orders', ['razorpayOrderId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_razorpayOrderId'), table_name='orders')
    op.drop_index(op.f('ix_orders_createdAt'), table_name='orders')
    op.drop_index(op.f('ix_jerseys_categoryId'), table_name='jerseys')
    op.create_table('carts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('carts_userId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pkey')),
    sa.UniqueConstraint('userId', name=op.f('carts_userId_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cart_items',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cartId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jerseyId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cartId'], ['carts.id'], name=op.f('cart_items_cartId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jerseyId'], ['jerseys.id'], name=op.f('cart_items_jerseyId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey')),
    sa.UniqueConstraint('cartId', 'jerseyId', name=op.f('cart_items_cart_id_jersey_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
